services:
  mysql:
    build: .
    ports:
      - "33060:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'testdb'
      MYSQL_USER: 'testuser'
      MYSQL_PASSWORD: 'p@ssw0rd'
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
volumes:
  mysql_data:
