services:
  db2:
    image: icr.io/db2_community/db2
    container_name: db2server
    hostname: db2server
    privileged: true
    ports:
      - "50005:50000"
    env_file:
      - env_list
    volumes:
      - db2_data:/database
    restart: always
volumes:
  db2_data:
